export const categories = [
  "AIDS",
  "Advanced Placement",
  "All-New Kindle Fire HD Audio",
  "Anger Management",
  "Architecture",
  "Astronomy & Space Science",
  "Bacteriology",
  "Beauty & Fashion",
  "Biostatistics",
  "Boxing",
  "Business & Management",
  "Campaigns & Battlefields",
  "Catholic",
  "Child Psychology",
  "Circus",
  "Cognitive Psychology",
  "Common Core",
  "Conspiracies",
  "Court Rules",
  "Cultural Studies",
  "Decision-Making & Problem Solving",
  "Diagnosis",
  "Divorce",
  "ESL",
  "Eldercare",
  "Entertaining & Holidays",
  "Ethnic & International",
  "Family Life",
  "Fish & Sharks",
  "Former Soviet Republics & Siberia",
  "Gaia",
  "Georgia",
  "Greek",
  "Harlequin Luna",
  "Herbal Remedies",
  "Home & Community Care",
  "Humor",
  "Industrial & Product Design",
  "International Children's",
  "Jesus",
  "Kindle Default Dictionaries",
  "Kidren's",
  "Jesus",
  "Kindle Default Dictionaries",
  "Kindle Reading Lights",
  "Language Experience Approach",
  "Liberation",
  "Louis L'Amour",
  "Malpractice",
  "Meals",
  "Mental Health",
  "Miming",
  "Motivational",
  "Mysticism",
  "Network Administration",
  "Nigeria",
  "Oahu",
  "Optics",
  "PCs",
  "Particle Physics",
  "Personality Disorders",
  "Piloting & Flight Instruction",
  "Porcelain & China",
  "Prince Edward Island",
  "Psychics",
  "Radar",
  "Relationships",
  "Rhythm & Blues",
  "Russian & Former Soviet Union",
  "Scandinavia",
  "Secretarial Aids & Training",
  "Showers",
  "Social Policy",
  "Southern Africa",
  "Sports Memorabilia & Cards",
  "Strokes",
  "Sydney",
  "Television & Radio",
  "Tips",
  "Tribal & Ethnic",
  "Urban",
  "Violence",
  "Web Browsers",
  "Wireless & Mobile Technology",
  "Writing, Research & Publishing Guides",
];
